In [31]:
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

In [65]:
df=pd.read_csv(r'C:\Users\visha\OneDrive\Scaler Academy\Datasets\planets.csv')
df.head(10)

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
5  Radial Velocity       1         185.840   4.80     76.39  2008
6  Radial Velocity       1        1773.400   4.64     18.15  2002
7  Radial Velocity       1         798.500    NaN     21.41  1996
8  Radial Velocity       1         993.300  10.30     73.10  2008
9  Radial Velocity       2         452.800   1.99     74.79  2010

In [66]:
df.isna().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [67]:
cols = ['number', 'orbital_period', 'mass', 'distance', 'year']
scaler = MinMaxScaler()
df[cols] = pd.DataFrame(scaler.fit_transform(df[cols]), columns = cols)
df.head(10)

            method    number  orbital_period      mass  distance  year
0  Radial Velocity  0.000000        0.000369  0.283897  0.008948  0.68
1  Radial Velocity  0.000000        0.001198  0.088269  0.006542  0.76
2  Radial Velocity  0.000000        0.001045  0.103871  0.002176  0.88
3  Radial Velocity  0.000000        0.000446  0.775968  0.012857  0.72
4  Radial Velocity  0.000000        0.000707  0.419916  0.013899  0.80
5  Radial Velocity  0.000000        0.000254  0.191884  0.008830  0.76
6  Radial Velocity  0.000000        0.002429  0.185483  0.001977  0.52
7  Radial Velocity  0.000000        0.001094       NaN  0.002360  0.28
8  Radial Velocity  0.000000        0.001361  0.411915  0.008443  0.76
9  Radial Velocity  0.166667        0.000620  0.079467  0.008641  0.84

In [69]:
imputer = KNNImputer(n_neighbors=5)
df[cols] = pd.DataFrame(imputer.fit_transform(df[cols]),columns = cols)
df.head(10)

            method    number  orbital_period      mass  distance  year
0  Radial Velocity  0.000000        0.000369  0.283897  0.008948  0.68
1  Radial Velocity  0.000000        0.001198  0.088269  0.006542  0.76
2  Radial Velocity  0.000000        0.001045  0.103871  0.002176  0.88
3  Radial Velocity  0.000000        0.000446  0.775968  0.012857  0.72
4  Radial Velocity  0.000000        0.000707  0.419916  0.013899  0.80
5  Radial Velocity  0.000000        0.000254  0.191884  0.008830  0.76
6  Radial Velocity  0.000000        0.002429  0.185483  0.001977  0.52
7  Radial Velocity  0.000000        0.001094  0.068522  0.002360  0.28
8  Radial Velocity  0.000000        0.001361  0.411915  0.008443  0.76
9  Radial Velocity  0.166667        0.000620  0.079467  0.008641  0.84

In [70]:
df.isna().sum()

method            0
number            0
orbital_period    0
mass              0
distance          0
year              0
dtype: int64